os: linux
dist: xenial
language: node_js
node_js: lts/*

script:
  - npm run quality:check
  - NODE_ENV=production npm run build

deploy:
  - provider: npm
    on:
      branch: main
      tags: true
      repo: taylorgrinn/logo
    email: grinntaylor@gmail.com
    api_key: $NPM_TOKEN

  - provider: pages
    on:
      branch: main
      repo: taylorgrinn/logo
    github_token: $GITHUB_TOKEN
    local_dir: dist
